export const podcasts = [
    {
        id: 1,
        title: "The Literary Voyage: #1",
        guest: 'Lars Håvard and Ingrid Solveig',
        description: "A thrilling exploration of alternative realities and the choices that shape our destinies.",
        image: require("./podcastImages/podcast(1).jpg"),
        link: 'soundcloud.......',
    },
    {
        id: 2,
        title: "The Literary Voyage: #2",
        guest: 'Hikaru Yamashita',
        description: "A thrilling exploration of alternative realities and the choices that shape our destinies.",
        image: require("./podcastImages/podcast(2).jpg"),
        link: 'soundcloud.......',
    },
    {
        id: 3,
        title: "The Literary Voyage: #3",
        guest: 'Karl Hoffmann',
        description: "A thrilling exploration of alternative realities and the choices that shape our destinies.",
        image: require("./podcastImages/podcast(3).jpg"),
        link: 'soundcloud.......',
    },
    {
        id: 4,
        title: "The Literary Voyage: #4",
        guest: 'Sofia Ullman',
        description: "A thrilling exploration of alternative realities and the choices that shape our destinies.",
        image: require("./podcastImages/podcast(4).jpg"),
        link: 'soundcloud.......',
    },
    {
        id: 5,
        title: "The Literary Voyage: #5",
        guest: 'William Torstensson',
        description: "A thrilling exploration of alternative realities and the choices that shape our destinies.",
        image: require("./podcastImages/podcast(5).jpg"),
        link: 'soundcloud.......',
    },
];