export const products = [
  {
    id: 1,
    title: 'Beatrice Fitzwilliams new book "What If?"',
    price: 299,
    description: "A thrilling exploration of alternative realities and the choices that shape our destinies.",
    longDescription: "A thrilling exploration of alternative realities and the choices that shape our destinies. Fitzwilliams masterfully intertwines different timelines, creating a captivating narrative that keeps readers on the edge of their seats. Each chapter reveals new dimensions and profound insights into the human condition.",
    category: "Science Fiction",
    image: require("./productImages/book(1).jpg"),
    alt1: 'Explore Beatrice Fitzwilliams new book "What If?"',
    alt2: "Intriguing questions about alternate realities and choice",
  },
  {
    id: 2,
    title: "Little Mysteries",
    price: 159,
    description: "A collection of short stories filled with intrigue and unexpected twists.",
    longDescription: "A collection of short stories filled with intrigue and unexpected twists. Each tale unravels a new enigma, inviting readers to become amateur detectives. The author’s sharp storytelling and clever plots will keep you guessing until the very end.",
    category: "Mystery",
    image: require("./productImages/book(2).jpg"),
    alt1: "Enchanting enigmas and captivating adventures",
    alt2: "",
  },
  {
    id: 3,
    title: "Beer Heaven",
    price: 199,
    description: "Discover the best brews from around the world and the stories behind them.",
    longDescription: "Discover the best brews from around the world and the stories behind them. This guide explores the rich histories and unique flavors of various beers, making it a must-have for enthusiasts. Detailed profiles and tasting notes make it easy to find your next favorite brew.",
    category: "Non-Fiction",
    image: require("./productImages/book(3).jpg"),
    alt1: "Discover the secrets of craft beer from brewing to tasting!",
    alt2: "",
  },
  {
    id: 4,
    title: "The Ugly Duckling",
    price: 129,
    description: "A timeless tale of transformation and self-discovery for all ages.",
    longDescription: "A timeless tale of transformation and self-discovery for all ages. This classic story highlights the importance of inner beauty and self-acceptance. With beautiful illustrations and an enduring message, it continues to inspire generations.",
    category: "Children's Literature",
    image: require("./productImages/book(4).jpg"),
    alt1: "A beautifully illustrated tale about transformation and self-discovery",
    alt2: "",
  },
  {
    id: 5,
    title: "Elderly Globetrotters",
    price: 359,
    description: "Join a group of spirited seniors on their adventures around the world.",
    longDescription: "Join a group of spirited seniors on their adventures around the world. Their journeys are filled with humor, wisdom, and the occasional mishap, offering a refreshing perspective on travel. This heartwarming narrative celebrates life and the joy of discovering new places at any age.",
    category: "Travel",
    image: require("./productImages/book(5).jpg"),
  },
  {
    id: 6,
    title: "Wings",
    price: 399,
    description: "An inspiring journey of personal growth and overcoming obstacles.",
    longDescription: "An inspiring journey of personal growth and overcoming obstacles. Through challenges and triumphs, the protagonist learns the true meaning of resilience and strength. This motivational story encourages readers to embrace their own journeys with courage and hope.",
    category: "Self-Help",
    image: require("./productImages/book(6).jpg"),
  },
  {
    id: 7,
    title: "Damsel",
    price: 359,
    description: "A gripping tale of courage and resilience in the face of adversity.",
    longDescription: "A gripping tale of courage and resilience in the face of adversity. Set against a historical backdrop, this novel brings to life the struggles and triumphs of its heroine. Rich in detail and emotion, it’s a story that will stay with you long after the final page.",
    category: "Historical Fiction",
    image: require("./productImages/book(7).jpg"),
  },
  {
    id: 8,
    title: "WW2: Echoes",
    price: 599,
    description: "A detailed account of the events and personal stories from World War II.",
    longDescription: "A detailed account of the events and personal stories from World War II. This comprehensive volume captures the heroism and heartbreak of the era, through the eyes of those who lived it. It is a tribute to the enduring spirit of humanity during times of conflict.",
    category: "History",
    image: require("./productImages/book(8).jpg"),
  },
  {
    id: 9,
    title: "Super Wizard",
    price: 159,
    description: "A magical adventure of a young wizard discovering his true potential.",
    longDescription: "A magical adventure of a young wizard discovering his true potential. As he navigates the challenges of his newfound powers, he uncovers secrets that change his world forever. This enchanting tale is filled with wonder, danger, and the power of friendship.",
    category: "Fantasy",
    image: require("./productImages/book(9).jpg"),
  },
  {
    id: 10,
    title: "Crazy",
    price: 299,
    description: "A rollercoaster story of unexpected events and wild twists.",
    longDescription: "A rollercoaster story of unexpected events and wild twists. Every chapter brings new surprises that will keep readers guessing. The fast-paced narrative and dynamic characters make it an exhilarating read from start to finish.",
    category: "Thriller",
    image: require("./productImages/book(10).jpg"),
  },
  {
    id: 11,
    title: "The Ultimate Drink Guide",
    price: 399,
    description: "The go-to guide for mixing the perfect drinks for any occasion.",
    longDescription: "The go-to guide for mixing the perfect drinks for any occasion. From classic cocktails to innovative new mixes, this book covers it all. Step-by-step instructions and expert tips ensure that every drink is a success.",
    category: "Cookbooks",
    image: require("./productImages/book(11).jpg"),
  },
  {
    id: 12,
    title: "Computers For Dummies",
    price: 199,
    description: "A beginner's guide to understanding and using computers effectively.",
    longDescription: "A beginner's guide to understanding and using computers effectively. Clear instructions and practical advice make complex concepts accessible. This book is an invaluable resource for anyone looking to improve their tech skills.",
    category: "Technology",
    image: require("./productImages/book(12).jpg"),
  },
  {
    id: 13,
    title: "Whispers of Serenity",
    price: 599,
    description: "Lose yourself in its gripping tale of adventure and redemption.",
    longDescription: "Lose yourself in its gripping tale of adventure and redemption. With twists that will leave you breathless, it's a must-read for any book lover!",
    category: "Fantasy",
    image: require("./productImages/book(13).jpg"),
  },
  {
    id: 14,
    title: "Vincent",
    price: 299,
    description: "Embark on a whimsical journey through the life of Vincent, the interdimensional artist, and discover the extraordinary sources of his inspiration.",
    longDescription: "Embark on a whimsical journey through the life of Vincent, the interdimensional artist, and discover the extraordinary sources of his inspiration. Join Vincent as he ventures beyond the boundaries of reality, guided by visions of alternate realms and mystical encounters. This imaginative audiobook invites you to explore the depths of his vivid imagination, where cosmic wonders and fantastical beings fuel his creative spirit. Step into a world where art and magic intertwine, and witness the boundless imagination of Vincent van Gogh.",
    category: "Fantasy",
    image: require("./productImages/audiobook(1).jpg"),
},
  {
    id: 15,
    title: "Reflections by the Moonlit Pond",
    price: 249,
    description: "A chilling tale of terror and mystery set in the year 1674, by the eerie moonlit pond.",
    longDescription: "A chilling tale of terror and mystery set in the year 1674, by the eerie moonlit pond. In the stillness of the night, shadows dance and whispers echo through the trees. As the protagonist uncovers dark secrets and faces unseen horrors, the line between reality and nightmare blurs, leaving listeners on edge.",
    category: "Horror",
    image: require("./productImages/audiobook(2).jpg"),
  },
  {
    id: 16,
    title: "A Summer Saga",
    price: 299,
    description: "An epic tale of love, loss, and adventure set in a picturesque summer landscape.",
    longDescription: "An epic tale of love, loss, and adventure set in a picturesque summer landscape. The characters’ journeys are as compelling as the vibrant settings. This audiobook is a heartfelt story that evokes the warmth and nostalgia of summer.",
    category: "Romance",
    image: require("./productImages/audiobook(3).jpg"),
  },
  {
    id: 17,
    title: "DR. Raven",
    price: 199,
    description: "A captivating mystery thriller featuring the enigmatic Dr. Raven.",
    longDescription: "A captivating mystery thriller featuring the enigmatic Dr. Raven. Each case he tackles is more perplexing than the last, with unexpected twists. This audiobook is perfect for fans of suspense and complex character-driven stories.",
    category: "Mystery",
    image: require("./productImages/audiobook(4).jpg"),
  },
  {
    id: 18,
    title: "Exclusive Philip & Pen - Pen",
    price: 1399,
    description: "Experience the epitome of writing luxury with the Exclusive Philip & Pen Pen.",
    longDescription: "Experience the epitome of writing luxury with the Exclusive Philip & Pen Pen. Meticulously crafted to perfection, this exquisite pen exudes elegance and sophistication in every stroke. Its smooth gliding tip effortlessly captures your thoughts, while its sleek design adds a touch of refinement to your writing experience. Elevate your writing to new heights with the Elegance in Ink, and make every word a masterpiece.",
    category: "Accessories",
    image: require("./productImages/other(1).jpg"),
  },
  {
    id: 19,
    title: "Artistic Notebook for Creative Minds",
    price: 239,
    description: "Unleash your creativity with our vibrant notebook, designed to inspire brilliance on every page.",
    longDescription: "Unleash your creativity with our vibrant notebook, designed to inspire brilliance on every page. Crafted with premium-quality paper, this notebook provides the perfect canvas for your thoughts and ideas. Whether you're sketching, writing, or brainstorming, let this notebook be your trusted companion in bringing your imagination to life.",
    category: "Accessories",
    image: require("./productImages/other(2).jpg"),
  },
  {
    id: 20,
    title: "Filip Pennsäter - Developer",
    price: 0,
    description: "A priceless, hardworking, skilled, and dedicated developer.",
    longDescription: "Introducing an invaluable asset to any development team, a hardworking, skilled, and dedicated developer. With a passion for innovation and a commitment to excellence, this individual brings unparalleled expertise and creativity to every project. As a priceless member of the team, their contributions transcend mere code, elevating the quality and success of each endeavor.",
    category: "Tech Wizardry",
    image: require("./productImages/other(3).jpg"),
  },
];